name: grafana-otel

services:
  lgtm:
    image: "grafana/otel-lgtm:latest"
    platform: linux/amd64 #Temp https://github.com/grafana/docker-otel-lgtm/pull/37
    ports:
      - "3000:3000" # Grafana
      - "4317:4317" # GRPC
      - "4318:4318" # HTTP

networks:
  default:
    name: lgtm-network
    driver: bridge