global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  
  - job_name: 'otelcollector'
    static_configs:
      - targets: [ 'otelcollector:8889' ]